# This is a basic workflow to help you get started with Actions

name: Caller

# Controls when the workflow will run 
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["test"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-central-pipeline:
      uses: SamuelAtUiPath/Actions-Pipelines/.github/workflows/called-pipeline.yml@main
      with:
        PROJECT_JSON_PATH: GitHubActions\project.json
        TENANT_NAME: Mars
      secrets: inherit
