# This is a basic workflow to help you get started with Actions

name: Caller

on:
  push:
    branches:
      - test
      - prod
  pull_request:
    branches:
      - test
      - prod

  workflow_dispatch:

jobs:
  echo-environment-name:
      runs-on: ubuntu-latest
      environment: ${{ github.ref_name }}  # This dynamically sets the environment based on the branch name
      steps:
        - name: Show environment name
          run: | 
            echo "Environment: ${{ github.ref_name }}"
            
  call-central-pipeline:
      uses: SamuelAtUiPath/Actions-Pipelines/.github/workflows/called-pipeline.yml@main
      with:
        PROJECT_JSON_PATH: GitHubActions\project.json
        TENANT_NAME: ${{ vars.TENANT_NAME }}  # Access TENANT_NAME from the environment's vars
      secrets: inherit
      
  
        
      

